# Generated by Django 3.2.18 on 2023-05-17 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_nickname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='color',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
