# Generated by Django 3.2.18 on 2023-05-15 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='moviecollection',
            name='movie_poster',
            field=models.CharField(default='', max_length=200),
        ),
    ]
