# Generated by Django 3.2.18 on 2023-05-17 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_movielike'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moviecollection',
            name='movie_poster',
            field=models.CharField(default='', max_length=200, null=True),
        ),
    ]
